### ISSUE TITLE
Maya 2022

### ISSUE THREAD

**Issue by blazinglazer** [dtzxporter/cast#11]
Looks like cast.py and castplugin.py need to be updated for Maya 2022:

`// Error: file: D:/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316:  (cast) // `

**Comment by dtzxporter** [comment]
You checked off the wrong file. You only check off 'castplugin.py' not 'cast.py'.

**Comment by blazinglazer** [comment]
Unfortunately neither 'castplugin.py' nor 'cast.py' are able to be checked in Maya 2022, so I think this is still an open issue :(

**Comment by dtzxporter** [comment]
@blazinglazer Is this still an issue?

Enable: https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2015/ENU/Maya/files/Debugging-optimizing-and-troubleshooting-Showing-the-calling-stack-when-an-error-occurs-htm.html and try again

**Comment by blazinglazer** [comment]
sadly it still is returning an error:

`// Error: file: C:/Program Files/Autodesk/Maya2022/scripts/startup/autoLoadPlugin.mel line 40: name 'xrange' is not defined
# Traceback (most recent call last):
#   File "C:/Program Files/Autodesk/Maya2022/bin/plug-ins/castplugin.py", line 12, in <module>
#     if xrange is None:
# NameError: name 'xrange' is not defined // 
// Warning: file: C:/Program Files/Autodesk/Maya2022/scripts/startup/autoLoadPlugin.mel line 40: Failed to run file: C:/Program Files/Autodesk/Maya2022/bin/plug-ins/castplugin.py // 
// Error: file: C:/Program Files/Autodesk/Maya2022/scripts/startup/autoLoadPlugin.mel line 40:  (castplugin) // 
// AbcExport v1.0 using Alembic 1.7.5 (built Nov 30 2020 18:40:46)
// Warning: file: C:/Program Files/Autodesk/Maya2022/scripts/startup/autoLoadPlugin.mel line 40: No initializePlugin() function
 // 
// Error: file: C:/Program Files/Autodesk/Maya2022/scripts/startup/autoLoadPlugin.mel line 40:  (cast) // 
// AbcImport v1.0 using Alembic 1.7.5 (built Nov 30 2020 18:40:46)
// Warning: file: C:/Program Files/Autodesk/Maya2022/scripts/others/supportRenderers.mel line 67: The renderer "arnold" used by this scene, is not currently available. The "mayaSoftware" renderer will be used instead. To prevent this message from being displayed in the future, set the environment variable: MAYA_NO_WARNING_FOR_MISSING_DEFAULT_RENDERER=1 // 
// Warning: file: C:/Program Files/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316: No initializePlugin() function
 // 
// Error: file: C:/Program Files/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316:  (cast) // 
// Error: file: C:/Program Files/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316: name 'xrange' is not defined
# Traceback (most recent call last):
#   File "C:/Program Files/Autodesk/Maya2022/bin/plug-ins/castplugin.py", line 12, in <module>
#     if xrange is None:
# NameError: name 'xrange' is not defined // 
// Warning: file: C:/Program Files/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316: Failed to run file: C:/Program Files/Autodesk/Maya2022/bin/plug-ins/castplugin.py // 
// Error: file: C:/Program Files/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316:  (castplugin) // 
`

**Comment by dtzxporter** [comment]
Can you try this file:
https://github.com/dtzxporter/cast/blob/master/plugins/maya/castplugin.py

**Comment by DirupT** [comment]
> Can you try this file: https://github.com/dtzxporter/cast/blob/master/plugins/maya/castplugin.py

Hello, I am trying to use this add on to use additive animations in a video I watched. (Since they don't work with blender)

I am using Maya 2022.1 and got the same error message the previous poster had, I used your updated file and no longer got any errors but now things seems buggy, first of all when I import something the mesh is gone. [Link to reference](https://gyazo.com/3d43d18b7599732931abdaa9e59fce5e). Secondly, importing cast files isn't work either.

Here is code from the script editor

`performFileDropAction ("C:/Users/DirupT/Downloads/Legion/exported_files/models/ptpov_alternator_smg/ptpov_alternator_smg_LOD0.cast");
file -import -type "Cast"  -ignoreVersion -ra true -mergeNamespacesOnClash false -namespace "ptpov_alternator_smg_LOD0"  -pr  -importFrameRate true  -importTimeRange "override" "C:/Users/DirupT/Downloads/Legion/exported_files/models/ptpov_alternator_smg/ptpov_alternator_smg_LOD0.cast";
// Error: line 0: TypeError: file S:/Maya_2022_DI/build/RelWithDebInfo/runTime/Python37/Lib/site-packages/maya/OpenMaya.py line 6220: in method 'new_MIntArray', argument 1 of type 'int const []'
Additional information:
Wrong number or type of arguments for overloaded function 'new_MIntArray'.
  Possible C/C++ prototypes are:
    MIntArray::MIntArray()
    MIntArray::MIntArray(MIntArray const &)
    MIntArray::MIntArray(int const [],unsigned int)
    MIntArray::MIntArray(unsigned int,int) // 
// File read in  0.29 seconds.
// Error: line 0: Error reading file. // 
performFileDropAction ("C:/Users/DirupT/Downloads/Legion/exported_files/animations/ptpov_alternator_smg/ads_in_0.cast");
file -import -type "Cast"  -ignoreVersion -ra true -mergeNamespacesOnClash false -namespace "ads_in_0"  -pr  -importFrameRate true  -importTimeRange "override" "C:/Users/DirupT/Downloads/Legion/exported_files/animations/ptpov_alternator_smg/ads_in_0.cast";
// Error: line 0: RuntimeError: file E:/Maya2022/bin/plug-ins/cast maya/castplugin.py line 353: (kInvalidParameter): Object does not exist // 
// File read in  0.018 seconds.
// Error: line 0: Error reading file. // `

Thanks for the plugin, I am using the trial version of Maya and cannot downgrade versions otherwise I would.
